### PR TITLE
login page desinged

### LINKED ISSUE #1: Login Page is not working whidvndkj
@bhavi140201  djbdjbcjbjebckjb

### PR DESCRIPTION
**Pull request by hellomraza**
desing succesfully logi page 

Fixes #1

### CODE REVIEW

File: src/pages/LoginPage/LoginPage.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import React from "react";
 import "./LoginPage.css";
-const LoginPage = () => <h1>LoginPage</h1>;
+const LoginPage = () => <h1>LoginPage Desined</h1>;
```
Comment (hellomraza) [inline src/pages/LoginPage/LoginPage.js:3]: worn cmdbnksdbj

**Review by hellomraza — COMMENTED** [review]
dcdcd

File: src/pages/LoginPage/LoginPage.js (hunk 1 above)
Comment (hellomraza) [reply src/pages/LoginPage/LoginPage.js:3]: #1
